#!/usr/bin/env node
/**
 * Builds the two deliverables from one source:
 *   dist/gas/      — the Apps Script project (clasp push, or paste file by file)
 *   dist/preview/  — the same form as a standalone page, nothing submitted
 *
 * Generated alongside the form: Rules.gs from src/rules/*.json, and Schema.gs
 * from docs/parent-request-register/schema.csv + lookups.csv, so the register's
 * headers are always the documented ones.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DOCS = path.join(ROOT, '..', '..', 'docs', 'parent-request-register');
const src = p => fs.readFileSync(path.join(ROOT, 'src', p), 'utf8');
const HEADER = '// GENERATED by build.js — edit src/, then run `npm run build`.\n';

function parseCsv(text) {
  const rows = []; let row = [], cell = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (q) {
      if (ch === '"' && text[i + 1] === '"') { cell += '"'; i++; }
      else if (ch === '"') q = false;
      else cell += ch;
    } else if (ch === '"') q = true;
    else if (ch === ',') { row.push(cell); cell = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(cell); rows.push(row); row = []; cell = '';
    } else cell += ch;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  const [head, ...body] = rows.filter(r => r.some(c => c !== ''));
  return body.map(r => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ''])));
}

// ---------------------------------------------------------------- inputs
const shared = src('engine.js') + '\n' + src('messages.js');
if (/<\/script/i.test(shared)) throw new Error('shared code must not contain </script');

const rulesDir = path.join(ROOT, 'src', 'rules');
const RULES_BY_YEAR = {};
for (const f of fs.readdirSync(rulesDir).filter(f => f.endsWith('.json')).sort()) {
  const r = JSON.parse(fs.readFileSync(path.join(rulesDir, f), 'utf8'));
  if (r.academicYear + '.json' !== f) throw new Error(`${f}: academicYear is ${r.academicYear}`);
  RULES_BY_YEAR[r.academicYear] = r;
}

const schema = parseCsv(fs.readFileSync(path.join(DOCS, 'schema.csv'), 'utf8'));
const SCHEMA = {};
for (const r of schema) (SCHEMA[r.tab] = SCHEMA[r.tab] || []).push([Number(r.order), r.field]);
for (const t in SCHEMA) SCHEMA[t] = SCHEMA[t].sort((a, b) => a[0] - b[0]).map(x => x[1]);
const LOOKUPS = parseCsv(fs.readFileSync(path.join(DOCS, 'lookups.csv'), 'utf8')).map(r => [r.list, r.value, r.note]);

const form = src('form.html');
if (form.includes('<?')) throw new Error('form.html must not contain "<?" — it is an Apps Script template');
for (const marker of ['<!--@SHARED-->', '/*@BOOT*/null']) {
  if (form.split(marker).length !== 2) throw new Error(`form.html must contain ${marker} exactly once`);
}
const json = o => JSON.stringify(o).replace(/</g, '\\u003c');

// ---------------------------------------------------------------- dist/gas
const gas = path.join(ROOT, 'dist', 'gas');
fs.rmSync(gas, { recursive: true, force: true });
fs.mkdirSync(gas, { recursive: true });
const put = (name, body) => fs.writeFileSync(path.join(gas, name), body);

put('Shared.gs', HEADER + shared);
put('SharedJs.html', '<script>\n' + shared + '\n</script>\n');
put('Rules.gs', HEADER + 'var RULES_BY_YEAR = ' + JSON.stringify(RULES_BY_YEAR, null, 2) + ';\n');
put('Schema.gs', HEADER + 'var SCHEMA = ' + JSON.stringify(SCHEMA, null, 2) + ';\n\nvar LOOKUPS = ' + JSON.stringify(LOOKUPS, null, 0).replace(/\],\[/g, '],\n  [') + ';\n');
// Function replacements: a string replacement would expand "$'" and "$&" — and the
// shared code contains "'−$' : '$'" — splicing the rest of the page into the script.
const fill = (html, marker, text) => html.replace(marker, () => text);
put('Form.html', fill(fill(form, '<!--@SHARED-->', "<?!= include('SharedJs'); ?>"), '/*@BOOT*/null', '<?!= boot ?>'));
for (const f of fs.readdirSync(path.join(ROOT, 'src', 'gas'))) {
  fs.copyFileSync(path.join(ROOT, 'src', 'gas', f), path.join(gas, f));
}

// ---------------------------------------------------------------- dist/preview
const preview = path.join(ROOT, 'dist', 'preview');
fs.mkdirSync(preview, { recursive: true });
const boot = { mode: 'preview', view: 'parent', lang: 'en', today: '2026-03-01', rules: RULES_BY_YEAR, example: true };
fs.writeFileSync(path.join(preview, 'index.html'),
  fill(fill(form, '<!--@SHARED-->', '<script>\n' + shared + '\n</script>'), '/*@BOOT*/null', json(boot)));

const files = fs.readdirSync(gas);
console.log(`dist/gas: ${files.length} files (${files.join(', ')})`);
console.log(`dist/preview/index.html: ${fs.statSync(path.join(preview, 'index.html')).size} bytes`);
console.log(`schema: ${Object.entries(SCHEMA).map(([t, h]) => `${t} ${h.length}`).join(', ')} · lookups ${LOOKUPS.length} · rule years ${Object.keys(RULES_BY_YEAR).join(', ')}`);
